import { parse } from 'csv-parse/sync';
import { CITE_STATES, READ_STATES } from '../src/shared/types';

/** 種類の振り分け (migrations/0004_entry_kinds.sql と同じ規則) */
const KIND_RFC_RULE =
  "lower(doi) LIKE '10.17487/rfc%' OR publisher = 'RFC Editor (IETF)' OR title GLOB 'RFC [0-9]*:*' OR (substr(lower(bibkey), 1, 3) = 'rfc' AND substr(bibkey, 4, 1) GLOB '[0-9]' AND length(ltrim(substr(lower(bibkey), 4), '0123456789')) <= 1 AND length(substr(bibkey, 4)) - length(ltrim(substr(lower(bibkey), 4), '0123456789')) <= 5)";
const KIND_DRAFT_RULE =
  "publisher = 'IETF (Internet-Draft)' OR lower(bibkey) GLOB 'draft-[a-z0-9]*-[a-z0-9]*' OR lower(title) GLOB 'draft-*-[0-9][0-9]:*'";

/** layout は旧 GAS 版のカード配置シート。ライブラリ UX 版では使わないが、旧手順の引数を壊さないため受け取って無視する。 */
export interface SheetCsvs { main: string; tags?: string; projects?: string; layout?: string }
export interface ImportSummary { entries: number; tags: number; projects: number; cites: number; dateFallbacks: number }

const HEADERS = ['追加日', 'タグ', 'タイトル', '概要', 'URL', 'DOI', '年', '出版国', '出版社', 'ジャーナル',
  'Impact Factor', 'カンファレンス', 'CORE Ranking', 'BibTeXキー', '読了状態', 'メモ', '引用状態'] as const;

export function sqlStr(v: string): string {
  return "'" + String(v ?? '').replace(/\u0000/g, '').replace(/'/g, "''") + "'";
}

function matchDate(s: string): string | null {
  const raw = String(s || '').trim();
  const m =
    raw.match(/^(\d{4})[\/\-.](\d{1,2})[\/\-.](\d{1,2})/) ??
    raw.match(/^(\d{4})年(\d{1,2})月(\d{1,2})日/);
  if (!m) return null;
  return `${m[1]}-${m[2]!.padStart(2, '0')}-${m[3]!.padStart(2, '0')}`;
}

export function normalizeDate(s: string, fallback: string): string {
  return matchDate(s) ?? fallback;
}

function rows(csv: string): string[][] {
  return parse(csv, { bom: true, relax_column_count: true, skip_empty_lines: false }) as string[][];
}

/** 1 列目だけを持つ管理シート (ヘッダ行を除く) */
function firstColumn(csv: string | undefined): string[] {
  if (!csv) return [];
  return rows(csv).slice(1).map((r) => String(r[0] ?? '').trim()).filter(Boolean);
}

const splitList = (v: string) => String(v || '').split(/[,、]/).map((t) => t.trim()).filter(Boolean);

/** "プロジェクト名: 状態, ..." を解析する。同じプロジェクトが複数回現れた場合は最後の値が勝つ
 * (旧 GAS 版 parseCites_ がオブジェクトに詰めていたのと同じ挙動。cites の PK (entry_id, project_id) 違反を防ぐ)。 */
function parseCites(v: string): [string, string][] {
  const map = new Map<string, string>();
  for (const pair of String(v || '').split(/[,、]/)) {
    const i = pair.lastIndexOf(':');
    if (i < 0) continue;
    const name = pair.slice(0, i).trim();
    const state = pair.slice(i + 1).trim();
    if (name && (CITE_STATES as readonly string[]).includes(state)) map.set(name, state);
  }
  return [...map];
}

export function buildImportSql(csvs: SheetCsvs, today: string): { sql: string; summary: ImportSummary } {
  const main = rows(csvs.main);
  const header = (main[0] ?? []).map((h) => String(h).trim());
  const col = (name: (typeof HEADERS)[number]) => header.indexOf(name);
  if (col('タイトル') < 0) throw new Error('メインシートの見出し行に「タイトル」列がありません。ヘッダ行付きで CSV を書き出してください。');
  const get = (r: string[], name: (typeof HEADERS)[number]) => { const i = col(name); return i >= 0 ? String(r[i] ?? '').trim() : ''; };

  const out: string[] = ['-- generated by scripts/import-sheet.ts', '-- 空の D1 に 1 回だけ実行すること (冪等ではない)'];
  const tagIds = new Map<string, number>();
  const projectIds = new Map<string, number>();
  const idOf = (map: Map<string, number>, name: string) => { if (!map.has(name)) map.set(name, map.size + 1); return map.get(name)!; };
  for (const t of firstColumn(csvs.tags)) idOf(tagIds, t);
  for (const p of firstColumn(csvs.projects)) idOf(projectIds, p);

  const entryTagStmts: string[] = [];
  const citeStmts: string[] = [];
  let entryId = 0;
  let dateFallbacks = 0;
  for (const r of main.slice(1)) {
    const title = get(r, 'タイトル');
    if (!title) continue;
    entryId++;
    const read = get(r, '読了状態');
    const addedRaw = get(r, '追加日');
    const added = matchDate(addedRaw);
    if (addedRaw && !added) dateFallbacks++;
    const values = [
      String(entryId), sqlStr(added ?? today), sqlStr(title), sqlStr(get(r, '概要')), sqlStr(get(r, 'URL')),
      sqlStr(get(r, 'DOI')), sqlStr(get(r, '年')), sqlStr(get(r, '出版国')), sqlStr(get(r, '出版社')), sqlStr(get(r, 'ジャーナル')),
      sqlStr(get(r, 'Impact Factor')), sqlStr(get(r, 'カンファレンス')), sqlStr(get(r, 'CORE Ranking')), sqlStr(get(r, 'BibTeXキー')),
      sqlStr((READ_STATES as readonly string[]).includes(read) ? read : '未読'), sqlStr(get(r, 'メモ')),
    ];
    out.push(`INSERT INTO entries (id, added, title, summary, url, doi, year, country, publisher, journal, impact_factor, conference, core, bibkey, read, note) VALUES (${values.join(', ')});`);
    Array.from(new Set(splitList(get(r, 'タグ')))).forEach((t, i) => {
      entryTagStmts.push(`INSERT INTO entry_tags (entry_id, tag_id, position) VALUES (${entryId}, ${idOf(tagIds, t)}, ${i});`);
    });
    for (const [name, state] of parseCites(get(r, '引用状態'))) {
      citeStmts.push(`INSERT INTO cites (entry_id, project_id, state) VALUES (${entryId}, ${idOf(projectIds, name)}, ${sqlStr(state)});`);
    }
  }
  for (const [name, id] of tagIds) out.push(`INSERT INTO tags (id, name, sort_order) VALUES (${id}, ${sqlStr(name)}, ${id - 1});`);
  for (const [name, id] of projectIds) out.push(`INSERT INTO projects (id, name, sort_order) VALUES (${id}, ${sqlStr(name)}, ${id - 1});`);
  out.push(...entryTagStmts, ...citeStmts);
  // 種類の振り分け (migrations/0004_entry_kinds.sql と同じ規則)。旧シートには種類の列が無い
  out.push(
    `UPDATE entries SET kind = 'rfc' WHERE ${KIND_RFC_RULE};`,
    `UPDATE entries SET kind = 'draft' WHERE kind = 'paper' AND (${KIND_DRAFT_RULE});`,
  );

  return {
    sql: out.join('\n') + '\n',
    summary: { entries: entryId, tags: tagIds.size, projects: projectIds.size, cites: citeStmts.length, dateFallbacks },
  };
}
